services:
  postgres:
    image: postgres:15-alpine
    container_name: vnair_postgres
    environment:
      POSTGRES_DB: vnair_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
